<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'SchwarzesSachsenCore\Filter\ImageUploadFilter'   => __DIR__ . '/src/SchwarzesSachsenCore/Filter/ImageUploadFilter.php',
  'SchwarzesSachsenCore\Filter\UploadForm'          => __DIR__ . '/src/SchwarzesSachsenCore/Filter/MultiUploadFilter.php',
  'SchwarzesSachsenCore\Controller\IndexController' => __DIR__ . '/src/SchwarzesSachsenCore/Controller/IndexController.php',
  'SchwarzesSachsenCore\Service\ServiceFactory'     => __DIR__ . '/src/SchwarzesSachsenCore/Service/ServiceFactory.php',
  'SchwarzesSachsenCore\Service\AbstractService'    => __DIR__ . '/src/SchwarzesSachsenCore/Service/AbstractService.php',
  'SchwarzesSachsenCore\Upload\Upload'              => __DIR__ . '/src/SchwarzesSachsenCore/Upload/Upload.php',
  'SchwarzesSachsenCore\Form\UploadForm'            => __DIR__ . '/src/SchwarzesSachsenCore/Form/UploadForm.php',
  'SchwarzesSachsenCore\Form\MultiUploadForm'       => __DIR__ . '/src/SchwarzesSachsenCore/Form/MultiUploadForm.php',
  'SchwarzesSachsenCore\Images\Resize'              => __DIR__ . '/src/SchwarzesSachsenCore/Images/Resize.php',
  'SchwarzesSachsenCore\Module'                     => __DIR__ . '/Module.php',
);
