<?php $children = $this->viewModel()
    ->getCurrent()
    ->getChildren();
$ourView  = $children[0];?>
<?php echo $this->doctype(); ?>
<?php $ourViewe = $ourView->error; ?>
<html lang="de_DE">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Admininterface'))->setSeparator(' - ')
                ->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
                                         'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.10.0.custom.min.css')?>

        <!-- Scripts -->
        <?php echo $this->inlineScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript',
                                            array('conditional' => 'lt IE 9'))
                                      ->prependFile($this->basePath() . '/js/bootstrap.js')
                                      ->prependFile($this->basePath() . '/js/jquery-1.9.0.js')
                                      ->appendFile($this->basePath() . '/js/jquery.form.js')
                                      ->appendFile($this->basePath() . '/js/jquery-ui-1.10.0.custom.min.js')
                                      ->appendFile($this->basePath() . '/js/ui-script.js')
                                      ->appendFile($this->basePath() . '/js/customscripts.js')
                                      ->appendFile($this->basePath() . '/js/multiUpload.js')?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
            <div class="nav-collapse">
                <ul class="nav">
                    <form class="navbar-search pull-right" method="post" action="<?php echo $this->url('search'); ?>">
                        <input type="text" name="search" class="search-query" placeholder="Suchen...">
                        <input type="submit" id="submitbutton" name="submit" value="submit"
                               style="display:none;"
                        />
                    </form>
                    <li class="dropdown">
                        <a href="/" class="dropdown-toggle" data-toggle="dropdown">
                        Administrationsmenü<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('administration') ?>">Adminhome</a></li>
                            <li><a href="<?php //echo $this->url('zfcuser/register', array('action' => 'register')) ?>">
                                neuen Benutzer anlegen
                                </a>
                            </li>
                            <li><a href="<?php echo $this->url('useradmin' ) ?>">Userverwaltung</a></li>
                            <li><a href="<?php echo $this->url('routeadmin') ?>">Routenverwaltung</a></li>
                            <li><a href="<?php //echo $this->url('zfcuser/logout') ?>">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container_content">
        <?php if (!empty($ourViewe) && is_array($ourViewe)) : ?>
        <?php foreach ($ourViewe as $fMessage) : ;?>
        <div class="alert alert-error">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <strong>Fehler:</strong> <?php echo $this->translate($fMessage); ?>
        </div>
        <?php endforeach; ?>
        <?php elseif (!empty($ourViewe) && ($ourViewe)) :?>
        <div class="alert alert-error">
          <a class="close" data-dismiss="alert" href="#">×</a>
          <strong>Fehler:</strong> <?php echo $this->translate($ourViewe); ?>
        </div>
        <?php endif;?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 - <?php echo date('Y') ?> by S-P-IT.de | Alle Rechte vorbehalten.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
